#!/bin/bash
###################################
# $Id: backup 379 2012-04-02 08:43:42Z netkiller $
# Author: netkiller@msn.com
# Home:	http://netkiller.github.com
###################################
BACKUP_HOST=""
BACKUP_USER=""
BACKUP_PASS=""
BACKUP_DIR=/backup/www
#Number of copies
COPIES=30
####################################
LOGFILE='/var/tmp/test.log'
TAR='tar'
RSYNC="rsync"
WEEK=$(date -u +%A)
# date -u +%a
# date -u +%w
TIMEPOINT=$(date -u +%Y-%m-%d)
RSYNC_OPTS="-auz --delete --log-file=$LOGFILE"
####################################
test ! -w $BACKUP_DIR && echo "Error: $BACKUP_DIR is un-writeable." && exit 0

umask 0077

for dirname in $(ls -1 /www)
do
	test ! -d "$BACKUP_DIR/$dirname" && mkdir -p "$BACKUP_DIR/$dirname"
	echo "$dirname:"
	for domainname in $(ls -1 /www/$dirname)
	do
		echo " - $domainname"
		backup_dir=$BACKUP_DIR/$dirname/$domainname/$WEEK
		mkdir -p ${backup_dir}
 		$RSYNC $RSYNC_OPTS /www/$dirname/$domainname/* $backup_dir
	done
 	#$RSYNC $RSYNC_OPTS /www/$dirname $BACKUP_DIR/$dirname/$TIMEPOINT
	#$TAR zcvf $BACKUP_DIR/$dirname.$TIMEPOINT.tgz /www/$dirname
done
find $BACKUP_DIR -type f -mtime +$COPIES -delete
